### ISSUE TITLE
 does the end2end_ohem detect well?

### ISSUE THREAD

**Issue by 646677064** [onkarganjewar/cmpe295-masters-project#2]
great work. @onkarganjewar  I'm ready to train my own data  with your work and code. had you get a good result with resnet101 for detecting?  my  data set consist of 1000 images of beers (in bottle ,or can 330ml~500ml). the result of mine (end2end) is bad with the Ross Girshick 's version of vgg-net. the rectangles are all not right . how was  the result of your end2end_ohem and alternative ？

**Comment by onkarganjewar** [comment]
Yes, I have trained a PASCAL VOC 2007 dataset with resnet-101 end2end_ohem and got nearly ~78% mAP.

However, I have not designed this faster-rcnn-resnet model on my own. My work is mere a reflection of the research/work carried out by @Eniac-Xie in [this](https://github.com/Eniac-Xie/faster-rcnn-resnet) repository. I'm still studying all the [modifications](https://github.com/Eniac-Xie/faster-rcnn-resnet#modification) made by @Eniac-Xie.
