### ISSUE TITLE
Measure distance of the objects from the camera

### ISSUE THREAD

**Issue by ghost** [onkarganjewar/cmpe295-masters-project#5]
Hi
Do you have any idea to measure distance of objects from camera? i am going use this in mobile app but i dont know sb have worked on it or not ? just i find this https://www.youtube.com/watch?v=o3Ky_EdHVrA&t=411s&pbjreload=10

**Comment by onkarganjewar** [comment]
Hey, 

No, I don't. I tried researching for the same, though. I didn't have enough time to implement this feature. You can check with the Udacity's [SDNDC](https://www.udacity.com/course/self-driving-car-engineer-nanodegree--nd013). I stumbled onto [this](https://medium.com/towards-data-science/vehicle-detection-and-distance-estimation-7acde48256e1) blog back then. There are many open-source implementations/research available which you can refer. Thanks.

Hope it helps!
